name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: create .env file at root
      run: touch .env
          && echo "${{secrets.ENV}}" > .env

    - name: upload .env file at root
      uses: actions/upload-artifact@v2
      with:
        name: .env
        path: .env

    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag qcard-ai
